Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "private_network", ip: "192.168.56.11"
  config.vm.hostname = "attacker"
  config.vm.provision "shell", path: "provision.sh"
end
