Vagrant.configure("2") do |config|
  config.vm.define "attacker" do |attacker|
    attacker.vm.box = "kalilinux/rolling"
    attacker.vm.hostname = "attacker"

    # Network
    attacker.vm.network "private_network", ip: "192.168.56.10"
    attacker.vm.network "forwarded_port", guest: 6080, host: 6082  # noVNC
    attacker.vm.network "forwarded_port", guest: 5901, host: 5902  # VNC
    attacker.vm.network "forwarded_port", guest: 22, host: 2223    # SSH

    # Provisioning
    attacker.vm.provision "shell", path: "provision.sh"

    # Resources
    attacker.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = 3072
      vb.cpus = 2
    end
  end
end
