Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  
  config.vm.hostname = "victim"
  config.vm.network "private_network", ip: "192.168.56.12"
  config.vm.network "forwarded_port", guest: 6080, host: 6080
  
  config.vm.provision "shell", path: "provision.sh"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = 2048  # Allocate more memory for GUI
    vb.cpus = 2           # Optional: Increase CPU

  end
end
